spring:
  profiles:
    active: KEYS
    include: KEYS
  h2:
    console:
      enabled:


  datasource:
    url: ${jdbc.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${jdbc.username}
    password: ${jdbc.password}

  jpa:
    hibernate:
      format_sql: true
      show_sql: true
      ddl-auto: update

logging:
    level:
      root: INFO

server:
  error:
    include-exception: false # Response? Exception ?? ??
    include-message: always # Response? Exception Message ?? ??
    include-stacktrace: on_param # Response? Stack Trace ?? ??
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

# S3 버킷 설정 (AWS)
cloud:
  aws:
    credentials:
      accessKey: ${aws.access-key}
      secretKey: ${aws.secret-key}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ${aws.s3.bucket}
      #url: ${aws.s3.bucket.url}

  # multipart 사이즈 설정
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB