spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:yoseobara
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      format_sql: true
      show_sql: true
      ddl-auto: update

server:
  error:
    include-exception: false
    include-message: always
    include-stacktrace: on_param
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
